// <auto-generated />
using System;
using BookRec.Infrastructure.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookRec.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(BookRecContext))]
    [Migration("20190701175159_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BookRec")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookRec.Infrastructure.EntityFramework.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Authors");

                    b.Property<string>("Categories");

                    b.Property<string>("ContainsImageBubbles");

                    b.Property<string>("Country");

                    b.Property<string>("ImageLink");

                    b.Property<string>("LanguageCode");

                    b.Property<string>("MaturityRating");

                    b.Property<int>("PageCount");

                    b.Property<string>("PreviewLink");

                    b.Property<string>("PrintType");

                    b.Property<bool>("PublicDomain");

                    b.Property<DateTime>("PublishedDate");

                    b.Property<string>("Publisher");

                    b.Property<string>("Subtitle");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
