namespace BookRec.Tools.Migration
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    public static class BookCategories
    {
        public static string[] GetSearchQueries()
            => new string[]
            {
                "Arts & Music",
                "Music",
                "Painting",
                "Performing Arts",
                "Photography",
                "Sculpture",
                "Biographies",
                "Ethnic & Cultural",
                "Europe",
                "Historical",
                "Leaders & Notable People",
                "Military",
                "Business",
                "Finance",
                "Economics",
                "Industries",
                "International",
                "Careers",
                "Kids",
                "Animals",
                "Action & Adventure",
                "Activities, Crafts & Games",
                "Activity Books",
                "Cars & Trains",
                "Comics",
                "Comic Books",
                "Comic Strips",
                "Dark Horse",
                "DC Comics",
                "Fantasy",
                "Computers & Tech",
                "Apple",
                "CAD",
                "Certification",
                "Computer Science",
                "Databases",
                "Cooking",
                "Baking",
                "BBQ",
                "Preserving",
                "Culinary Arts",
                "Desserts",
                "Hobbies & Crafts",
                "Antiques",
                "Clay",
                "Collecting",
                "Fashion",
                "Jewelry Making",
                "Edu & Reference",
                "Catalogs",
                "Colleges",
                "Curriculum",
                "Dictionaries",
                "Education",
                "Gay & Lesbian",
                "Biographies",
                "GLBT Books",
                "Family",
                "History",
                "Literature & Fiction",
                "Health & Fitness",
                "Aging",
                "Alternative Medicine",
                "Beauty, Grooming & Style",
                "Children's Health",
                "Disease & Ailments",
                "History",
                "Medieval",
                "Middle Eastern",
                "Military",
                "Modern",
                "Native American",
                "Home & Garden",
                "Architecture",
                "Flowers",
                "Fruit",
                "Home Decorating",
                "Home Improvement",
                "Horror",
                "Ghosts",
                "Paranormal",
                "Supernatural",
                "Vampires",
                "Zombies",
                "Horror",
                "Ghosts",
                "Paranormal",
                "Supernatural",
                "Vampires",
                "Zombies",
                "Entertainment",
                "Entertainers",
                "Games",
                "Humor",
                "Brain Teasers",
                "Movies",
                "Literature & Fiction",
                "Foreign Language",
                "Genre Fiction",
                "History & Criticism",
                "Poetry",
                "World Literature",
                "Medical",
                "Administration",
                "Allied Health",
                "Basic Sciences",
                "Clinical",
                "Dentistry",
                "Medical",
                "Administration",
                "Allied Health",
                "Basic Sciences",
                "Clinical",
                "Dentistry",
                "Mysteries",
                "Conspiracy",
                "Crime",
                "Detective",
                "Mysteries",
                "Suspense",
                "Parenting",
                "Family Relationships",
                "Fertility",
                "Infants",
                "Pregnancy & Childbirth",
                "Special Needs",
                "Social Sciences",
                "Anarchy",
                "Canadian Politics",
                "Civil Rights",
                "Socialism",
                "Comparative Politics",
                "Religion",
                "Agnosticism",
                "Astrology",
                "Atheism",
                "Buddhism",
                "Christian",
                "Romance",
                "Time Travel",
                "Vampires",
                "Western",
                "Contemporary",
                "Erotica",
                "Science & Math",
                "Agricultural Sciences",
                "Anatomy",
                "Animals",
                "Astronomy",
                "Biology",
                "Sci-Fi & Fantasy",
                "Role Playing",
                "Anthologies",
                "Horror",
                "Humor",
                "Space",
                "Self-Help",
                "Abuse",
                "Addictions",
                "Anger Management",
                "Anxieties & Phobias",
                "Social Skills",
                "Sports",
                "Soccer",
                "Training",
                "Survival Skills",
                "Water Sports",
                "Winter Sports",
                "Teen",
                "Teeneager",
                "Fantasy",
                "Historical Fiction",
                "Hobbies",
                "Horror",
                "Travel",
                "Africa",
                "Asia",
                "Canada",
                "Caribbean",
                "Europe",
                "True Crime",
                "Famous Criminals",
                "Murder & Mayhem",
                "Organized Crime",
                "Serial Killers",
                "Criminal Law",
                "Westerns",
                "Native American",
                "Humor",
                "Prairie Settlement",
                "Cowboys",
                "Gold Rush",
                "Offers",
                "ReadingRewards",
                "Teacher Discount",
                "Tell-a-Friend",
                "Gift Cards",
                "Free Shipping",
                "ThriftBooks Deals",
                "Special Editions",
                "Large Print",
                "Rare & Collectible",
                "First Editions",
                "Signed Copies",
                "Website",
                "Testimonials",
                "Blog",
                "Terms of Use",
                "Privacy Policy"
            };

        public static string[] GetSearchQueries2()
            => new string[]
            {
                "Action and adventure",
                "Art",
                "Alternate history",
                "Autobiography",
                "Anthology",
                "Biography",
                "Chick lit",
                "Book review",
                "Children's",
                "Cookbook",
                "Comic book",
                "Diary",
                "Coming-of-age",
                "Dictionary",
                "Crime",
                "Encyclopedia",
                "Drama",
                "Guide",
                "Fairytale",
                "Health",
                "Fantasy",
                "History",
                "Graphic novel",
                "Journal",
                "Historical fiction",
                "Math",
                "Horror",
                "Memoir",
                "Mystery",
                "Prayer",
                "Paranormal romance",
                "Religion, spirituality, and new age",
                "Picture book",
                "Textbook",
                "Poetry",
                "Review",
                "Political thriller",
                "Science",
                "Romance",
                "Self help",
                "Satire",
                "Travel",
                "Science fiction",
                "True crime",
                "Shortstory",
                "Suspense",
                "Thriller",
                "Young adult"
            };
    }
}
